### ISSUE TITLE
Add "on this page" table of contents to every page to help navigation within a page

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane.github.io#122]
I've seen in other docs sites the ability to have an auto generated "table of contents" for every page.  This can really help navigate on longer pages that have lots of content and therefore lots of scrolling.  Having a per page TOC can help jump to a specific section right way and generally navigate the long wall of text more easily.

An example page where this would be really helpful is the composition reference page: https://crossplane.io/docs/v1.4/reference/composition.html

An example from the CockroachDB docs can be found here: https://www.cockroachlabs.com/docs/stable/make-queries-fast.html

![Screen Shot 2021-09-22 at 5 36 48 PM](https://user-images.githubusercontent.com/4313439/134439604-1728c49c-6cbb-4368-91a7-7bb040d1c9e9.png)

Note that the "On this page" TOC scrolls along with the page, so it's always accessible, and the current section of the docs is highlighted within the TOC to give a clue as to your current location.  This is super helpful for navigation and would help the Crossplane docs too!

**Comment by plumbis** [comment]
+1. Will address with the upcoming redesign or shortly after.

**Comment by plumbis** [comment]
Fixed in theme-update branch.

![Screen Shot 2022-11-12 at 12 22 23 AM](https://user-images.githubusercontent.com/10537576/201458653-045f7a25-ea18-43c3-abe2-77cb9a8ffaa2.png)

**Comment by plumbis** [comment]
One more screenshot showing that it is static with the content scroll.

![Screen Shot 2022-11-12 at 12 22 59 AM](https://user-images.githubusercontent.com/10537576/201458671-6a1b1a77-3424-47f9-abf2-7c7e2e7e5bde.png)
