### ISSUE TITLE
Broken links in the hosted crossplane section

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane.github.io#124]
The links in https://crossplane.io/docs/v1.4/getting-started/install-configure.html#start-with-a-hosted-crossplane appear to be broken for `create` and `connect`:

> you can create and then connect to your hosted Crossplane cluster.

This is what the links currently point to:
Create: https://cloud.upbound.io/docs/getting-started/set-up-upbound-cloud
Connect: https://cloud.upbound.io/docs/getting-started/connect-to-your-platform

We should figure our more recent and better targets for these links, and get them updated.  Also worth backporting to previous docs versions.

**Comment by plumbis** [comment]
This content no longer exists, resolving.
