### ISSUE TITLE
Update banner with Incubation announcement

### ISSUE THREAD

**Issue by grantgumina** [crossplane/crossplane.github.io#126]
### What problem are you facing?
The banner on crossplane.io still mentions KubeCon EU '21.

![image](https://user-images.githubusercontent.com/372681/138568072-d330e316-0e29-4775-9a08-553277d44df6.png)

### How could we address your issue?
The banner could instead say:
`Crossplane is now a CNCF Incubating Project <LINK>` and link to https://blog.crossplane.io/crossplane-cncf-incubation/

**Comment by negz** [comment]
I'm pretty sure we just removed the banner recently.
