### ISSUE TITLE
Render h4 elements correctly

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane.github.io#132]
Currently, docs the use an `h4` element render it larger than an `h3` because the `h1` / `h2` / `h3` elements have CSS overridden in https://github.com/crossplane/crossplane.github.io/blob/5c829b27fdb41fe4a1212e6a0eb63c989ae7d3e0/css/docs.scss#L34, while `h4` does not so it falls back to https://github.com/crossplane/crossplane.github.io/blob/5c829b27fdb41fe4a1212e6a0eb63c989ae7d3e0/css/main.scss#L83. `h4` should also be added to `docs.scss`.

Example (`Manifests` and `Configurations` are `h3` while `Motivation` is `h4`):
![Screenshot from 2022-01-09 08-55-02](https://user-images.githubusercontent.com/31777345/148687682-2a262527-8606-4d3f-a2aa-d8e882bdb751.png)

cc @thephred

**Comment by plumbis** [comment]
I'll make sure this is addressed as part of the upcoming redesign.

**Comment by plumbis** [comment]
or....is it fixed with your PR from January?

**Comment by plumbis** [comment]
This is confirmed as fixed. Closing.

![Screen Shot 2022-10-10 at 9 47 49 AM](https://user-images.githubusercontent.com/10537576/194881175-42224c92-b25c-4efb-a37e-c1eb013e4067.png)
