### ISSUE TITLE
provide latest for direct doc links

### ISSUE THREAD

**Issue by natereid72** [crossplane/crossplane.github.io#140]
When we want to add a link to a specific doc in another doc, we have to embed a version in the rule. We can use `master` as version but that links to RC and throws a big red warning box.

Being able to simply provide the link to the doc with `latest` or no version in url at all would be useful.

**Comment by plumbis** [comment]
This should be solved by #149 
After it's merged let's double check and if not, I know what we can do to solve it.

**Comment by plumbis** [comment]
#149 didn't solve this. We wont' be able to provide this until we move to a new hosting platform in #98

**Comment by plumbis** [comment]
This is currently working in netlify dev. 
https://deploy-preview-173--crossplane.netlify.app/docs/latest/concepts/managed-resources.html

**Comment by plumbis** [comment]
Fixed with https://github.com/crossplane/crossplane.github.io/commit/645f3cdb10ad8a8f9f62e7f0daae55e9ce50a5fe

http://docs.crossplane.io/latest
