### ISSUE TITLE
Codeblock is not rendered in AWS wordpress steps

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane.github.io#15]
This looks like a similar issue to #14, where the Jekyll processing isn't handling certain markdown correctly.

See step 7 on https://crossplane.io/docs/master/workloads/aws/wordpress-aws.html#create-your-amazon-eks-cluster-vpc and the attached screenshot, where the codeblock (triple backticks) aren't being rendered correctly.

![Screenshot of bad docs site code block rendering](https://user-images.githubusercontent.com/4313439/50701357-690dc580-1002-11e9-9f09-83d24d6f0b99.png)

Note this renders OK in the github repo: https://github.com/crossplaneio/crossplane/blob/master/docs/workloads/aws/wordpress-aws.md#create-your-amazon-eks-cluster-vpc

**Comment by apaz037** [comment]
Ah, I definitely see this.  
Thank you for checking and verifying!
I will generate the Jekyll site locally the next time I look at this and verify that everything is rendering correctly and submit a subsequent PR for this issue.

**Comment by apaz037** [comment]
css also appears to be rendering the regions markdown too large:

<img width="573" alt="crossplane github io_aws_regions_css" src="https://user-images.githubusercontent.com/17068663/50703615-97db6a00-1009-11e9-9eaa-80e4064e6bba.png">

**Comment by jbw976** [comment]
Closing out this old issue - I don't think we still have this issue that i'm aware of
