### ISSUE TITLE
Can't see the search box in dark mode.

### ISSUE THREAD

**Issue by plumbis** [crossplane/crossplane.github.io#197]
![Screen Shot 2022-11-04 at 3 34 00 PM](https://user-images.githubusercontent.com/10537576/200060225-66e56b5b-efa0-4c88-8bcd-e899c7a82bee.png)

**Comment by Santosh1176** [comment]
I can't see the Search bar on big screens as well.
![crossplane](https://user-images.githubusercontent.com/91916466/200114010-2d6a8d39-8c3d-4a63-af01-2e1fafef7048.png)

**Comment by plumbis** [comment]
Thanks for the feedback!

We are redesigning the search box as part of an overall design change. Here is an example of the new search box in light mode: 

<img width="486" alt="Screen Shot 2022-11-05 at 2 14 22 PM" src="https://user-images.githubusercontent.com/10537576/200134949-5032120b-747c-4a67-9c6f-fee408a89adf.png">

**Comment by plumbis** [comment]
Fixed in theme-update branch.

(Style fixed, but search is temporarily disabled)
