### ISSUE TITLE
"Edit on Github" button broken for non-top-level pages

### ISSUE THREAD

**Issue by thephred** [crossplane/crossplane.github.io#21]
For example, on this page: https://crossplane.io/docs/master/workloads/gcp/wordpress-gcp.html
when you click "Edit on Github" it goes to: https://github.com/crossplaneio/crossplane/blob/master/docs/wordpress-gcp.md
but should go to: https://github.com/crossplaneio/crossplane/blob/master/docs/workloads/gcp/wordpress-gcp.md

**Comment by jbw976** [comment]
I don't see this problem anymore actually, so I'll close :)
