### ISSUE TITLE
Subsection headers should render self links

### ISSUE THREAD

**Issue by displague** [crossplane/crossplane.github.io#27]
Headings throughout the docs do not offer a link.  Inspecting the document reveals than an id attribute is present on headings but there is no linking aid available.

For example: https://crossplane.io/docs/v0.3/services-developer-guide.html#getting-started

I would expect a chain-link icon to appear when hovering over this title and I would expect that I could click that icon to have the link copied.

I would settle for the ability to right click on the heading or a linking aid and choose to copy the link that way.

**Comment by jbw976** [comment]
@connorchan @rathpc could something like what was merged recently in the rook.io docs help with this? https://github.com/rook/rook.github.io/pull/83

i would love having this functionality!! 💪

**Comment by rathpc** [comment]
> @connorchan @rathpc could something like what was merged recently in the rook.io docs help with this? [rook/rook.github.io#83](https://github.com/rook/rook.github.io/pull/83)
> 
> i would love having this functionality!! 💪

Yea, could probably borrow most of the changes since these two sites are built very similarly
