### ISSUE TITLE
Sync docs from stack repos

### ISSUE THREAD

**Issue by negz** [crossplane/crossplane.github.io#32]
Currently we need to keep all documentation we want on the website (including API type documentation) in the core Crossplane repo, even when documenting stack resources. Ideally we'd support syncing docs folders from each stack to form one cohesive set of documentation.

**Comment by negz** [comment]
It would also make sense to support syncing docs from other non-stack repos - i.e. crossplaneio/crossplane-runtime and crossplaneio/crossplane-tools.

**Comment by jbw976** [comment]
i think this isn't applicable anymore since we use doc.crds.dev for API docs now
