### ISSUE TITLE
Make non-latest version alert more apparent

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane.github.io#42]
Currently when a user goes to either `master` or a previous version of the docs a banner informs them they are not looking at the latest version's documentation. However, the alert could stand to be a bit more alarming as the current one does not really feel like a deterrent to reading older docs.

**Comment by jbw976** [comment]
Related to the suggestion in https://github.com/crossplane/crossplane.github.io/issues/107#issuecomment-834174904
