### ISSUE TITLE
Add required footer with Linux Foundation copyright text

### ISSUE THREAD

**Issue by jbw976** [crossplane/crossplane.github.io#54]
One of the final steps for onboarding Crossplane into the CNCF (https://github.com/cncf/toc/issues/466) is to add the required footer to the crossplane.io website.

We did this recently on https://rook.io/ in https://github.com/rook/rook.github.io/pull/90/files. Use that PR as a reference for the content that should be added to crossplane.io in a footer, obviously using the crossplane.io styling though 😎

**Comment by jbw976** [comment]
Re-opening until https://github.com/crossplane/crossplane.github.io/pull/55#issuecomment-662590222 is resolved

**Comment by rathpc** [comment]
@jbw976 This should now be resolved
