### ISSUE TITLE
Add Equinix Metal to landing page

### ISSUE THREAD

**Issue by hasheddan** [crossplane/crossplane.github.io#67]
There is currently significant work being done on the [Equinix Metal Provider](https://github.com/packethost/crossplane-provider-equinix-metal) and [Equinix Metal](https://metal.equinix.com/) should be included on our landing page :rocket: 

/cc @displague

**Comment by displague** [comment]
Here are three variations that should fit in the “There is a flavor” and “Started by Upbound” sections:

https://gist.github.com/displague/163c0fdf2ff15c52a58a3df4020c193a

**Comment by displague** [comment]
If the context includes text names under or beside each logo, it is preferable to use the "Fortress" logo with the text "Equinix Metal".

https://brand.equinix.com/equinix-visual-brand/logos/#fortress

**Comment by connorchan** [comment]
Hey @mattheilman — Could you look into adding the above logo to this image we're using on the homepage? 
![image](https://user-images.githubusercontent.com/8014678/98044441-bbc18f80-1ddb-11eb-86a7-cf412308d316.png)

**Comment by prasek** [comment]
agree would be great to have this ahead of KubeCon NA 🚀

**Comment by prasek** [comment]
@mattheilman here's the logo from https://metal.equinix.com/ 
![image](https://user-images.githubusercontent.com/284840/98959181-e5ec0f00-24b7-11eb-9411-57533a0261f3.png)

as @displague mentions above: it is preferable to use the "Fortress" logo with the text "Equinix Metal".
https://brand.equinix.com/equinix-visual-brand/logos/#fortress
