### ISSUE TITLE
Accept Cookie prompt comes up frequently

### ISSUE THREAD

**Issue by bassam** [crossplane/crossplane.github.io#97]
This keeps coming up even when I accept it. 

<img width="1104" alt="CleanShot 2021-04-05 at 10 15 24@2x" src="https://user-images.githubusercontent.com/1463491/113602827-fa13e280-95f7-11eb-8b4a-260b6eeff120.png">

**Comment by connorchan** [comment]
See: https://webkit.org/blog/9521/intelligent-tracking-prevention-2-3/

Safari is doing more to prevent user tracking by "curb[ing] third-party scripts’ use of first-party cookies for the purposes of cross-site tracking."

This involves capping the expiry of client-side cookies at 24 hours or 7 days.

**Comment by bassam** [comment]
7 days is better - is it at 24 hrs now?

**Comment by connorchan** [comment]
I'm not sure—it's determined by the browser, not by any setting within HubSpot itself

**Comment by plumbis** [comment]
We don't collect cookies and this alert no longer appears.
